## inspiration worthy -
##   https://github.com/KYDronePilot/SpaceEye/blob/df7ea24c8948f4197fb5ac3dbce9d2c796c8ac45/.github/workflows/ci.yaml

on:
  push:
    branches:
    - master
  workflow_dispatch:
    # Inputs the workflow accepts.
   
jobs:
  electron-app-build-release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [macos-latest, ubuntu-latest, windows-latest]
        os: [macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Snapcraft Action
        uses: samuelmeuli/action-snapcraft@v1.1.3

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # macOS code signing certificate
          mac_certs: ${{ secrets.mac_certs }}
          mac_certs_password: ${{ secrets.mac_certs_password }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          # release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          release: true

      ## https://github.com/samuelmeuli/action-electron-builder/issues/14
      # - name: Move Files
      #   shell: bash
      #   run: ./scripts/move_dist.sh

      # - name: Upload Linux Artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: jarvis-linux
      #     path: dist-linux

      # - name: Upload Mac Artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: jarvis-mac
      #     path: dist-mac

      # - name: Upload Win Artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: jarvis-win
      #     path: dist-win

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Jarvis
          path: packages/Jarvis*
